version: "3"

vars:
  BINARY_NAME: baseball
  BUILD_DIR: tmp
  MAIN_PATH: ./cli

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the baseball CLI
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PATH}}
    sources:
      - "**/*.sql"
      - "**/*.go"
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  rebuild:
    desc: Clean and rebuild
    cmds:
      - task: clean
      - task: build

  swagger:generate:
    desc: Generate Swagger/OpenAPI documentation
    cmds:
      - swag init --dir ./internal/api --generalInfo server.go --output ./internal/docs --parseDependency --parseInternal --md ./internal/api
      - task: swagger:fix
    sources:
      - "internal/**/*.go"
    generates:
      - "internal/docs/swagger.json"
      - "internal/docs/swagger.yaml"

  swagger:fix:
    desc: Fix generated swagger docs (remove LeftDelim/RightDelim fields)
    cmds:
      - |
        # Remove LeftDelim and RightDelim fields from generated docs.go
        # These fields cause build errors due to swag version incompatibility
        if [ -f internal/docs/docs.go ]; then
          sed -i.bak '/LeftDelim:/d; /RightDelim:/d' internal/docs/docs.go && rm -f internal/docs/docs.go.bak
          echo "✓ Fixed swagger docs (removed LeftDelim/RightDelim fields)"
        else
          echo "⚠ internal/docs/docs.go not found, skipping fix"
        fi

  swagger:fmt:
    desc: Format swagger comments
    cmds:
      - swag fmt

  swagger:clean:
    desc: Clean generated swagger files
    cmds:
      - rm -f internal/docs/docs.go internal/docs/swagger.json internal/docs/swagger.yaml

  db:migrate:
    desc: Run database migrations
    cmds:
      - ./{{.BUILD_DIR}}/{{.BINARY_NAME}} db migrate

  dev:setup:
    desc: Complete development setup
    cmds:
      - task: swagger:generate
      - task: build
      - task: db:migrate
      - echo ""
      - echo "Setup complete!"

  dev:reload:
    desc: Rebuild and restart server
    cmds:
      - task: swagger:generate
      - task: rebuild
      - echo ""
      - echo "Rebuild complete! Restart the server to pick up changes"
